name: example-environment
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - textblob
  - nltk=3.2.4
  - pip:
    - nbgitpuller
    - sphinx-gallery
    - pandas
    - matplotlib
    - textblob
